<?php
return[
    'title' => 'Acto de Grado Promoción XXXVI Pedro Cabello Poleo',
    'extra-1' => '“Queridos graduandos, hace pocos minutos cada uno de ustedes recibió el título que los acredita como profesionales, están prestos para la siguiente etapa, tienen las herramientas básicas para construir su futuro. En estos momentos tendrá mayor sentido los sacrificios, triunfos, fracasos experimentados a lo largo de estos años. Precisamente ahora, en estos momentos de remembranza, los invito a brindar un sentido homenaje a aquellos que sembraron en ustedes la semilla de la necesidad del saber, los que fueron acompañantes y alentadores en esta trayectoria: sus padres, familiares, profesores, amigos, compañeros.',
    'extra-2' => 'Queridos graduandos, quiero dejarles esta reflexión, en la intimidad de sus decisiones, ojalá una de ellas, sea el arraigo a nuestra tierra, no para sembrarse como árboles de sombra, pacientes, soportando calmadamente el batir de sus hojas, de acuerdo al viento que las sople.  A mi entender, ese arraigo debe ser como el del aborigen, empeñados en subsistir en el tiempo, en defender su cultura, su idiosincrasia, su lengua, la madre tierra que los vio nacer.',
    'extra-3' => 'No es tiempo de huir, es tiempo de arraigarnos y demostrar que si podemos. Tenemos el conocimiento, la capacidad, la voluntad y el deseo. Conocemos los errores y a los errados. Tenemos en ustedes: la vitalidad, la juventud. En nosotros, los mayores: la experiencia.  Emprendamos la siembra de la capacitación colectiva. En nuestras manos, el deber impostergable de volver a romper las cadenas y dar paso al gran futuro de nuestro país.',
    'extra-4' => 'No quisiera despedirme sin antes compartirles estas últimas palabras la educación agudiza el entendimiento, da cabida al razonamiento e incentiva la investigación. La educación es el arma más temida por los que por oficio engañan. La educación llama a la superación y esta va de la mano con el desarrollo. Actúen siempre apegados a sus principios, háganlos valer.',
    'extra-5' => 'Somos y seremos con mayor fortaleza aun, el Alma Mater del Caribe, de nuestra Margarita, de nuestra Venezuela.',
    'extra-6' => 'En su día y como nunca retumbarán las palabras del sempiterno maestro. Quiero concluir expresando uno de sus pensamientos. “Sólo la unidad del pueblo y la solidaridad de sus dirigentes, garantizan la grandeza de las naciones.” Andrés Bello.',
    'extra-7' => 'Que Dios y nuestra patrona, la Virgen del Valle los bendiga”.',
    'extra-8' => 'Extracto del discurso pronunciado por la rectora Antonieta Rosales de Oxford durante el Acto de Grado de la XXXVI Promoción Pro. Pedro Cabello Poleo, noviembre 2022.',
];
